name: Run Tests
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - run: pnpm install
      - run: pnpm test:ci
      - run: pnpm coverage

      - name: Extract coverage percentage
        run: |
          COVERAGE=$(node -pe "require('./coverage/coverage-summary.json').total.lines.pct")
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV

      - name: Create coverage badge
        run: |
          COLOR=$(node -e "console.log($COVERAGE > 80 ? 'green' : $COVERAGE > 50 ? 'yellow' : 'red')")
          curl -o coverage-badge.svg "https://img.shields.io/badge/Coverage-${COVERAGE}%25-${COLOR}"

      - name: Commit and push badge
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add coverage-badge.svg
          git commit -m "Update coverage badge" || echo "No changes to commit"
          git push
